### Ячейка 1: Импорты

In [34]:
# Ячейка 1: Импорты
import os
import gc
import sys
import json
import random
import time
import warnings
from pathlib import Path
from typing import List, Dict, Tuple, Optional

os.environ['KMP_DUPLICATE_LIB_OK']='TRUE'
print(f"KMP_DUPLICATE_LIB_OK set to: {os.environ.get('KMP_DUPLICATE_LIB_OK')}")

import numpy as np
import pandas as pd
import soundfile as sf
import librosa
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, Subset, random_split
from torch.nn.utils.rnn import pad_sequence
from torch.cuda.amp import GradScaler, autocast
from torch.optim.lr_scheduler import ReduceLROnPlateau, CosineAnnealingLR
from tqdm.notebook import tqdm
import Levenshtein # pip install python-Levenshtein
import mlflow # pip install mlflow

# Игнорировать предупреждения librosa/soundfile (опционально)
warnings.filterwarnings('ignore', category=UserWarning)
warnings.filterwarnings('ignore', category=FutureWarning)

print("PyTorch Version:", torch.__version__)
print("MLflow Version:", mlflow.__version__)
print("Levenshtein available:", "Levenshtein" in sys.modules)

KMP_DUPLICATE_LIB_OK set to: TRUE
PyTorch Version: 2.5.1+cu121
MLflow Version: 2.21.3
Levenshtein available: True

### Ячейка 2: Конфигурация (Централизованная)

In [35]:
# Ячейка 2: Конфигурация (Централизованная)

CONFIG = {
    # --- Режим работы ---
    "mode": {
        "calibration_mode": False, # True для быстрой калибровки, False для полного обучения
        "calibration_subset_size": 500, # Сколько сэмплов использовать в режиме калибровки
        "calibration_epochs": 5,
        "calibration_batch_size": 8,
        "full_epochs": 50, # Количество эпох для полного обучения
        "full_batch_size": 16, # Подбирать под VRAM с учетом AMP и Grad Accum
    },
    # --- Пути ---
    "paths": {
        "data_dir": "./", # Директория с train.csv, test.csv, sample_submission.csv
        "zip_file": "./morse_dataset.zip",
        # --- ИЗМЕНЕНИЕ ЗДЕСЬ ---
        # Указываем полный относительный путь к папке с аудиофайлами
        "audio_folder_name": "morse_dataset/morse_dataset",
        # --- КОНЕЦ ИЗМЕНЕНИЯ ---
        "output_dir": "./output", # Директория для сохранения моделей и результатов
        "mlflow_tracking_uri": None, # Опционально: "http://localhost:5000" или путь к локальной папке ./mlruns
    },
    # --- MLflow ---
    "mlflow": {
        "experiment_name": "Morse Code Recognition",
        "run_name_prefix": "morse_exp",
    },
    # --- Воспроизводимость ---
    "random_seed": 42,
    # --- Параметры аудио и признаков ---
    "audio": {
        "sample_rate": 8000,
        "n_mels": 32,        # <--- ТЮНИТЬ (было 12, пробуем больше)
        "n_fft": 512,        # <--- ТЮНИТЬ (было 128)
        "hop_length": 128,   # <--- ТЮНИТЬ (было 64)
        "fmin": 0,
        "fmax": 4200,        # Ограничиваем частоту сверху, как обсуждали
        "power": 2.0,        # Используем Linear Mel (не Log)
        "use_deltas": False, # <--- ТЮНИТЬ (True/False)
    },
    # --- Параметры аугментации ---
    "augmentation": {
        "apply_augmentations": True,
        "noise": {
            "apply": True,
            "min_snr_db": 10.0, # Минимальное отношение сигнал/шум
            "max_snr_db": 30.0,
        },
        "gain": {
            "apply": True,
            "min_gain_db": -6.0, # Ослабление до -6 дБ
            "max_gain_db": 6.0,  # Усиление до +6 дБ
        },
        "spec_augment": {
            "apply": True,
            "time_mask_param": 3,   # <--- ТЮНИТЬ (макс. ширина временной маски, было 0)
            "num_time_masks": 2,    # <--- ТЮНИТЬ (количество временных масок)
            "freq_mask_param": 5,   # <--- ТЮНИТЬ (макс. ширина частотной маски, было 1)
            "num_freq_masks": 2,    # <--- ТЮНИТЬ (количество частотных масок)
            "iid_masks": True,
        }
    },
    # --- Параметры модели ---
    "model": {
        "cnn_out_channels": [32, 64], # Каналы в Conv2d слоях
        "cnn_kernel_size": [(3, 3), (3, 3)], # Размеры ядер
        "cnn_stride": [(1, 1), (1, 1)],      # Шаги свертки
        "cnn_pool_kernel": [(1, 2), (1, 2)], # Размеры ядер MaxPool2d (сжимаем только время) <--- МЕНЬШЕ АГРЕССИИ
        "rnn_hidden_size": 256, # <--- ТЮНИТЬ (было 384)
        "rnn_layers": 2,
        "rnn_dropout": 0.2,
        "dropout": 0.2,
        # vocab_size будет добавлен автоматически позже
    },
    # --- Параметры обучения ---
    "training": {
        "device": "cuda" if torch.cuda.is_available() else "cpu",
        "num_workers": 0, # Для DataLoader
        "optimizer": "AdamW", # AdamW или Adam
        "learning_rate": 3e-4,
        "weight_decay": 1e-5,
        "scheduler": "ReduceLROnPlateau", # ReduceLROnPlateau или CosineAnnealingLR
        "lr_scheduler_patience": 5, # Для ReduceLROnPlateau
        "lr_scheduler_factor": 0.2, # Для ReduceLROnPlateau
        "lr_min": 1e-6,             # Для CosineAnnealingLR и ReduceLROnPlateau
        "use_amp": True, # Использовать Automatic Mixed Precision <--- ВАЖНО
        "gradient_accumulation_steps": 1, # <--- ТЮНИТЬ (увеличить, если батч мал)
        "gradient_clip_val": 1.0, # Ограничение градиента
        "val_split_ratio": 0.1, # Доля данных для валидации
        "early_stopping_patience": 10, # Количество эпох без улучшения для остановки
    },
    # --- CTC Параметры ---
    "ctc": {
        "blank_char": "<blank>", # Символ пустого токена
        "blank_idx": 0,          # Его индекс (обычно 0)
    }
}

# --- Выбор параметров в зависимости от режима ---
if CONFIG["mode"]["calibration_mode"]:
    CONFIG["training"]["epochs"] = CONFIG["mode"]["calibration_epochs"]
    CONFIG["training"]["batch_size"] = CONFIG["mode"]["calibration_batch_size"]
    CONFIG["training"]["early_stopping_patience"] = 3 # Быстрее останавливаемся в калибровке
else:
    CONFIG["training"]["epochs"] = CONFIG["mode"]["full_epochs"]
    CONFIG["training"]["batch_size"] = CONFIG["mode"]["full_batch_size"]

# --- Создание выходной директории ---
OUTPUT_DIR = Path(CONFIG["paths"]["output_dir"])
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# --- Сохранение конфига для воспроизводимости ---
config_save_path = OUTPUT_DIR / "config.json"
with open(config_save_path, 'w') as f:
    json.dump(CONFIG, f, indent=4)

print(f"Режим работы: {'Калибровка' if CONFIG['mode']['calibration_mode'] else 'Полное обучение'}")
print(f"Устройство: {CONFIG['training']['device']}")
print(f"Конфигурация сохранена в: {config_save_path}")
print(f"Ожидаемый путь к аудиофайлам: {Path(CONFIG['paths']['data_dir']) / CONFIG['paths']['audio_folder_name'] / '<имя_файла_из_csv>'}")

Режим работы: Полное обучение
Устройство: cuda
Конфигурация сохранена в: output\config.json
Ожидаемый путь к аудиофайлам: morse_dataset\morse_dataset\<имя_файла_из_csv>

### Ячейка 3: Утилиты и Настройка MLflow

In [36]:
# Ячейка 3: Утилиты и Настройка MLflow

def set_seed(seed):
    """Устанавливает seed для воспроизводимости."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        # Обеспечивает детерминированность, но может замедлить
        # torch.backends.cudnn.deterministic = True
        # torch.backends.cudnn.benchmark = False

def setup_mlflow(config):
    """Настраивает MLflow."""
    if config["paths"]["mlflow_tracking_uri"]:
        mlflow.set_tracking_uri(config["paths"]["mlflow_tracking_uri"])
    mlflow.set_experiment(config["mlflow"]["experiment_name"])
    print(f"MLflow Experiment: {config['mlflow']['experiment_name']}")
    print(f"MLflow Tracking URI: {mlflow.get_tracking_uri()}")

# Установка seed
set_seed(CONFIG["random_seed"])

# Настройка MLflow
setup_mlflow(CONFIG)

# Очистка памяти GPU (на всякий случай)
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    gc.collect()

MLflow Experiment: Morse Code Recognition
MLflow Tracking URI: file:///c:/Users/vasja/OneDrive/%D0%A0%D0%B0%D0%B1%D0%BE%D1%87%D0%B8%D0%B9%20%D1%81%D1%82%D0%BE%D0%BB/Morse_dev/MorseAudioDecoder/mlruns

### Ячейка 4: Загрузка и подготовка данных (CSV, Словарь)

In [37]:
# Ячейка 4: Загрузка и подготовка данных (CSV, Словарь)

def create_char_map(texts: List[str], blank_char: str) -> Tuple[Dict[str, int], Dict[int, str], int]:
    """Создает словари для преобразования символов в индексы и обратно."""
    # Проверка на NaN или другие нестроковые типы перед обработкой
    valid_texts = [str(text) for text in texts if pd.notna(text)]
    if len(valid_texts) < len(texts):
        print(f"Предупреждение: Обнаружено {len(texts) - len(valid_texts)} пустых или NaN значений в целевых текстах.")

    unique_chars = set(c for text in valid_texts for c in text)
    sorted_chars = sorted(list(unique_chars))

    char_to_int = {char: i + 1 for i, char in enumerate(sorted_chars)}
    char_to_int[CONFIG["ctc"]["blank_char"]] = CONFIG["ctc"]["blank_idx"] # Добавляем blank токен

    int_to_char = {i: char for char, i in char_to_int.items()}
    vocab_size = len(char_to_int)

    print(f"Размер словаря (включая blank): {vocab_size}")
    print(f"Символы словаря: {[int_to_char[i] for i in range(vocab_size)]}")
    return char_to_int, int_to_char, vocab_size

# Загрузка CSV
data_dir = Path(CONFIG["paths"]["data_dir"])
train_df = pd.read_csv(data_dir / "train.csv")
test_df = pd.read_csv(data_dir / "sample_submission.csv") # Используем sample submission для списка тестовых файлов

# --- Вывод имен столбцов для контроля ---
print("Столбцы в train_df:", train_df.columns)
print("Столбцы в test_df:", test_df.columns)
# --- КОНЕЦ ВЫВОДА ---

# --- УСТАНОВКА ПРАВИЛЬНЫХ ИМЕН СТОЛБЦОВ ---
train_file_column = 'id' # Столбец с ID/именем файла в train.csv
test_file_column = 'id'  # Столбец с ID/именем файла в sample_submission.csv
morse_code_column = 'message' # Столбец с кодом Морзе в train.csv
# --- КОНЕЦ УСТАНОВКИ ---

# Проверка наличия столбцов
if train_file_column not in train_df.columns:
    raise ValueError(f"Столбец '{train_file_column}' не найден в train.csv! Проверьте имена: {train_df.columns}")
if test_file_column not in test_df.columns:
     raise ValueError(f"Столбец '{test_file_column}' не найден в sample_submission.csv! Проверьте имена: {test_df.columns}")
if morse_code_column not in train_df.columns:
    raise ValueError(f"Столбец '{morse_code_column}' не найден в train.csv! Проверьте имена: {train_df.columns}")


# Создание словарей символов на основе ТРЕНИРОВОЧНЫХ данных
# Добавляем .astype(str) на случай, если там есть нестроковые значения
char_to_int, int_to_char, vocab_size = create_char_map(
    train_df[morse_code_column].astype(str).tolist(), # Используем правильное имя и преобразуем в строку
    CONFIG["ctc"]["blank_char"]
)
CONFIG["model"]["vocab_size"] = vocab_size # Сохраняем размер словаря в конфиг

# Абсолютный путь к папке с аудио
audio_folder_path = data_dir / CONFIG["paths"]["audio_folder_name"]
print(f"Путь к аудио: {audio_folder_path}")
# Проверка наличия папки (распаковку предполагаем выполненной)
if not audio_folder_path.is_dir():
     print(f"ВНИМАНИЕ: Папка с аудио {audio_folder_path} не найдена! Убедитесь, что архив распакован.")
     # Можно добавить код для распаковки здесь, если нужно

# Добавляем полный путь к файлам в DataFrame
# Убедимся, что имена файлов имеют расширение .opus
def create_full_path(filename, folder):
    filename_str = str(filename)
    # Добавляем .opus, если его нет (предполагаем, что все файлы opus)
    if not filename_str.endswith('.opus'):
        filename_str += '.opus'
    return folder / filename_str

train_df['full_path'] = train_df[train_file_column].apply(lambda x: create_full_path(x, audio_folder_path))
test_df['full_path'] = test_df[test_file_column].apply(lambda x: create_full_path(x, audio_folder_path))


print(f"Загружено {len(train_df)} тренировочных записей.")
print(f"Загружено {len(test_df)} тестовых записей.")
display(train_df.head(3))
# Проверим пример полного пути
print("\nПример полного пути к файлу:", train_df['full_path'].iloc[0])

Столбцы в train_df: Index(['id', 'message'], dtype='object')
Столбцы в test_df: Index(['id', 'message'], dtype='object')
Размер словаря (включая blank): 45
Символы словаря: ['<blank>', ' ', '#', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'А', 'Б', 'В', 'Г', 'Д', 'Е', 'Ж', 'З', 'И', 'Й', 'К', 'Л', 'М', 'Н', 'О', 'П', 'Р', 'С', 'Т', 'У', 'Ф', 'Х', 'Ц', 'Ч', 'Ш', 'Щ', 'Ъ', 'Ы', 'Ь', 'Э', 'Ю', 'Я']
Путь к аудио: morse_dataset\morse_dataset
Загружено 30000 тренировочных записей.
Загружено 5000 тестовых записей.

       id     message                           full_path
0  1.opus  03ЩУЫЛПИГХ  morse_dataset\morse_dataset\1.opus
1  2.opus  ЪЛТ0ДС6А3Г  morse_dataset\morse_dataset\2.opus
2  3.opus   5ЭКЫБЗХЯН  morse_dataset\morse_dataset\3.opus

Пример полного пути к файлу: morse_dataset\morse_dataset\1.opus

### Ячейка 5: Функции извлечения признаков и Аугментации Аудио

In [38]:
# Ячейка 5: Функции извлечения признаков и Аугментации Аудио

def add_noise(y: np.ndarray, sr: int, min_snr_db: float, max_snr_db: float) -> np.ndarray:
    """Добавляет Гауссов шум к аудиосигналу."""
    if len(y) == 0: return y
    snr_db = random.uniform(min_snr_db, max_snr_db)
    signal_power = np.mean(y**2)
    if signal_power == 0: return y # Избегаем деления на ноль для тишины
    noise_power = signal_power / (10**(snr_db / 10))
    noise = np.random.normal(0, np.sqrt(noise_power), len(y))
    return y + noise

def change_gain(y: np.ndarray, min_gain_db: float, max_gain_db: float) -> np.ndarray:
    """Изменяет громкость аудиосигнала."""
    if len(y) == 0: return y
    gain_db = random.uniform(min_gain_db, max_gain_db)
    gain_amplitude = 10**(gain_db / 20)
    return y * gain_amplitude

def get_features(
    audio_path: Path,
    sr: int,
    n_mels: int,
    n_fft: int,
    hop_length: int,
    fmin: int,
    fmax: int,
    power: float,
    use_deltas: bool,
    apply_noise: bool = False,
    noise_params: Optional[dict] = None,
    apply_gain: bool = False,
    gain_params: Optional[dict] = None
) -> Optional[np.ndarray]:
    """Загружает аудио, применяет аудио аугментации и извлекает Mel-спектрограммы (и дельты)."""
    try:
        y, current_sr = sf.read(audio_path, dtype='float32')

        # Ресемплинг, если необходимо
        if current_sr != sr:
            y = librosa.resample(y, orig_sr=current_sr, target_sr=sr)

        # --- Аудио Аугментации ---
        if apply_noise and noise_params:
            y = add_noise(y, sr, noise_params['min_snr_db'], noise_params['max_snr_db'])
        if apply_gain and gain_params:
            y = change_gain(y, gain_params['min_gain_db'], gain_params['max_gain_db'])

        # --- Извлечение Признаков ---
        mel_spec = librosa.feature.melspectrogram(
            y=y,
            sr=sr,
            n_fft=n_fft,
            hop_length=hop_length,
            n_mels=n_mels,
            fmin=fmin,
            fmax=fmax,
            power=power # Linear Mel
        )

        features = mel_spec # (n_mels, time)

        if use_deltas:
            delta1 = librosa.feature.delta(mel_spec, order=1)
            # delta2 = librosa.feature.delta(mel_spec, order=2) # Можно добавить и вторые дельты
            features = np.stack([mel_spec, delta1], axis=0) # (channels=2, n_mels, time)
        else:
             features = np.expand_dims(features, axis=0) # (channels=1, n_mels, time)

        # Транспонируем в (channels, time, n_mels) для удобства обработки в модели (Conv2d)
        features = features.transpose(0, 2, 1) # -> (C, T, F)

        return features

    except Exception as e:
        print(f"Ошибка обработки файла {audio_path}: {e}")
        return None

### Ячейка 6: Класс Dataset и Трансформация SpecAugment

In [39]:
# Ячейка 6: Класс Dataset и Трансформация SpecAugment
import torchaudio # Убедимся, что импортирован
from torch.utils.data import Subset # Убедимся, что импортирован
import numpy as np # Убедимся, что импортирован
import pandas as pd # Убедимся, что импортирован
import torch # Убедимся, что импортирован
from torch.utils.data import Dataset, DataLoader # Убедимся, что импортированы
import gc # Убедимся, что импортирован
from tqdm.notebook import tqdm # Убедимся, что импортирован

class SpecAugmentTransform(nn.Module):
    """Применяет SpecAugment с использованием torchaudio."""
    def __init__(self, aug_config: dict): # Переименовал аргумент для ясности
        super().__init__()
        # --- ИЗМЕНЕНИЕ ЗДЕСЬ: Правильный доступ к ключам ---
        # aug_config - это словарь, соответствующий CONFIG["augmentation"]
        # Проверяем наличие ключей перед доступом
        self.apply_spec_augment = aug_config.get("spec_augment", {}).get("apply", False)
        if not self.apply_spec_augment:
            self.time_masking = None
            self.freq_masking = None
            self.num_time_masks = 0
            self.num_freq_masks = 0
            return

        spec_cfg = aug_config.get("spec_augment", {}) # Получаем словарь spec_augment
        # --- КОНЕЦ ИЗМЕНЕНИЯ ---

        self.time_masking = None
        self.num_time_masks = spec_cfg.get("num_time_masks", 0)
        time_mask_param = spec_cfg.get("time_mask_param", 0)
        iid_masks = spec_cfg.get("iid_masks", True)

        if self.num_time_masks > 0 and time_mask_param > 0:
             self.time_masking = torch.nn.Sequential(
                 torchaudio.transforms.TimeMasking(
                    time_mask_param=time_mask_param,
                    p=1.0, # Применяем всегда, если вызвано
                    iid_masks=iid_masks
                )
             )

        self.freq_masking = None
        self.num_freq_masks = spec_cfg.get("num_freq_masks", 0)
        freq_mask_param = spec_cfg.get("freq_mask_param", 0)

        if self.num_freq_masks > 0 and freq_mask_param > 0:
            self.freq_masking = torch.nn.Sequential(
                 torchaudio.transforms.FrequencyMasking(
                    freq_mask_param=freq_mask_param,
                    iid_masks=iid_masks
                )
            )


    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x shape: (C, T, F)
        if not self.apply_spec_augment:
            return x

        # Транспонируем для torchaudio: (C, F, T)
        x_permuted = x.clone().permute(0, 2, 1)

        # Применяем маски нужное количество раз
        if self.freq_masking and self.num_freq_masks > 0:
            for _ in range(self.num_freq_masks):
                 x_permuted = self.freq_masking(x_permuted)

        if self.time_masking and self.num_time_masks > 0:
             for _ in range(self.num_time_masks):
                 x_permuted = self.time_masking(x_permuted)

        # Возвращаем исходную размерность: (C, T, F)
        return x_permuted.permute(0, 2, 1)


class MorseDataset(Dataset):
    def __init__(
        self,
        df: pd.DataFrame,
        char_to_int: Dict[str, int],
        audio_config: dict,
        aug_config: dict, # Этот словарь передается в SpecAugmentTransform
        text_column: str,
        feature_mean: Optional[np.ndarray] = None,
        feature_std: Optional[np.ndarray] = None,
        augment: bool = False
    ):
        self.df = df
        self.char_to_int = char_to_int
        self.audio_config = audio_config
        self.aug_config = aug_config # Сохраняем для аудио аугментаций
        self.augment = augment
        self.text_column = text_column
        # Передаем aug_config в SpecAugmentTransform
        self.spec_augment_transform = SpecAugmentTransform(aug_config) if augment else None

        # Нормализация
        self.mean = torch.tensor(feature_mean, dtype=torch.float32).unsqueeze(1).unsqueeze(2) if feature_mean is not None else None
        self.std = torch.tensor(feature_std, dtype=torch.float32).unsqueeze(1).unsqueeze(2) if feature_std is not None else None
        if self.std is not None:
             self.std = torch.clamp(self.std, min=1e-6)


    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        if idx >= len(self.df):
             raise IndexError("Индекс вне диапазона DataFrame")
        row = self.df.iloc[idx]
        audio_path = row['full_path']
        morse_text = row[self.text_column]

        # --- Используем self.aug_config для аудио аугментаций ---
        apply_noise = self.augment and self.aug_config.get("noise", {}).get("apply", False)
        apply_gain = self.augment and self.aug_config.get("gain", {}).get("apply", False)
        noise_params = self.aug_config.get("noise")
        gain_params = self.aug_config.get("gain")
        # --- КОНЕЦ ИСПОЛЬЗОВАНИЯ ---

        # Извлечение признаков
        features = get_features(
            audio_path,
            sr=self.audio_config["sample_rate"],
            n_mels=self.audio_config["n_mels"],
            n_fft=self.audio_config["n_fft"],
            hop_length=self.audio_config["hop_length"],
            fmin=self.audio_config["fmin"],
            fmax=self.audio_config["fmax"],
            power=self.audio_config["power"],
            use_deltas=self.audio_config["use_deltas"],
            apply_noise=apply_noise,
            noise_params=noise_params if apply_noise else None,
            apply_gain=apply_gain,
            gain_params=gain_params if apply_gain else None
        )

        if features is None:
            return None

        features_tensor = torch.tensor(features, dtype=torch.float32) # (C, T, F)

        # Нормализация
        if self.mean is not None and self.std is not None:
            features_tensor = (features_tensor - self.mean) / self.std

        # SpecAugment
        if self.augment and self.spec_augment_transform:
            features_tensor = self.spec_augment_transform(features_tensor)

        # Кодирование текста
        morse_text_str = str(morse_text)
        encoded_text = torch.tensor(
            [self.char_to_int.get(c, self.char_to_int[CONFIG["ctc"]["blank_char"]]) for c in morse_text_str],
            dtype=torch.long
        )

        input_length = torch.tensor(features_tensor.shape[1], dtype=torch.long) # T
        target_length = torch.tensor(len(encoded_text), dtype=torch.long)

        return features_tensor, encoded_text, input_length, target_length

# --- Расчет статистик нормализации ---
def calculate_norm_stats(dataset: Dataset, num_samples: int = 1000) -> Tuple[np.ndarray, np.ndarray]:
    """Рассчитывает среднее и стандартное отклонение по подвыборке датасета."""
    print(f"Расчет статистик нормализации по {num_samples} сэмплам...")
    if len(dataset) == 0:
        raise ValueError("Датасет для расчета нормализации пуст!")

    actual_num_samples = min(num_samples, len(dataset))
    if actual_num_samples == 0:
         raise ValueError("Недостаточно данных в датасете для расчета нормализации.")

    subset_indices = np.random.choice(len(dataset), actual_num_samples, replace=False)
    subset = Subset(dataset, subset_indices)

    loader = DataLoader(
        subset,
        batch_size=CONFIG["training"]["batch_size"] // 2,
        num_workers=0, # Устанавливаем 0
        collate_fn=lambda b: [item for item in b if item is not None]
    )

    all_features = []
    pbar = tqdm(loader, desc="Нормализация", total=len(loader))
    for batch in pbar:
        if not batch: continue
        features_list = [item[0] for item in batch if item is not None and item[0] is not None]
        all_features.extend([f.cpu() for f in features_list])
        del batch, features_list
        gc.collect()

    if not all_features:
        raise ValueError("Не удалось извлечь признаки для расчета нормализации.")

    num_channels = all_features[0].shape[0]
    sum_features = torch.zeros(num_channels, dtype=torch.float64)
    sum_sq_features = torch.zeros(num_channels, dtype=torch.float64)
    total_elements_per_channel = 0

    print("Начинаем агрегацию статистик...")
    for f in tqdm(all_features, desc="Агрегация стат.") :
        f_float64 = f.to(torch.float64)
        num_elements_in_sample = f.shape[1] * f.shape[2]
        if num_elements_in_sample == 0: continue

        sum_features += torch.sum(f_float64, dim=(1, 2))
        sum_sq_features += torch.sum(f_float64**2, dim=(1, 2))
        total_elements_per_channel += num_elements_in_sample

    if total_elements_per_channel == 0:
        raise ValueError("Нет данных для расчета нормализации (total_elements_per_channel = 0).")

    mean = (sum_features / total_elements_per_channel).numpy().astype(np.float32)
    variance = (sum_sq_features / total_elements_per_channel) - (sum_features / total_elements_per_channel)**2
    std = torch.sqrt(torch.clamp(variance, min=0.0)).numpy().astype(np.float32)

    print(f"Расчет завершен. Mean: {mean}, Std: {std}")
    if np.any(std < 1e-6):
        print("Предупреждение: Обнаружено очень маленькое или нулевое стандартное отклонение. Заменяю на 1e-6.")
        std = np.maximum(std, 1e-6)

    del all_features
    gc.collect()

    return mean, std

# Создаем временный датасет БЕЗ аугментаций для расчета нормализации
if train_df.empty:
    raise ValueError("DataFrame train_df пуст! Невозможно создать датасет.")

temp_train_ds_for_norm = MorseDataset(
    train_df, char_to_int, CONFIG["audio"], CONFIG["augmentation"],
    text_column='message', # Используем правильное имя столбца
    augment=False
)

# Расчет статистик
norm_sample_count = CONFIG["mode"]["calibration_subset_size"] if CONFIG["mode"]["calibration_mode"] else 2000
feature_mean, feature_std = calculate_norm_stats(temp_train_ds_for_norm, num_samples=norm_sample_count)

# Очистка временного датасета
del temp_train_ds_for_norm
gc.collect()

Расчет статистик нормализации по 2000 сэмплам...

Нормализация:   0%|          | 0/250 [00:00<?, ?it/s]

Начинаем агрегацию статистик...

Агрегация стат.:   0%|          | 0/2000 [00:00<?, ?it/s]

Расчет завершен. Mean: [8.478325], Std: [35.04799]

29

### Ячейка 7: Функция Collate

In [40]:
# Ячейка 7: Функция Collate

def collate_fn(batch: List[Optional[Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]]],
               blank_idx: int) -> Optional[Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]]:
    """
    Обрабатывает батч: фильтрует None, паддит признаки и тексты.
    Возвращает None, если батч пуст после фильтрации.
    """
    # 1. Фильтрация None элементов (если __getitem__ вернул None)
    batch = [b for b in batch if b is not None]
    if not batch:
        return None # Весь батч оказался плохим

    # 2. Разделение на компоненты
    # features: List[Tensor(C, T, F)], texts: List[Tensor(L)], ...
    features, texts, input_lengths, target_lengths = zip(*batch)

    # 3. Паддинг признаков (C, T, F) -> (B, C, T_max, F)
    # Мы паддим по временной оси T (dim=1)
    # batch_first=True не нужен для pad_sequence напрямую, но нужен для DataLoader
    # Нужно убедиться, что паддинг идет по нужной оси
    # Сначала сделаем (B, T_max, C, F) или (B, T_max, F, C)?
    # Модель ожидает (B, C, F, T) - значит паддим по T
    # features_padded = pad_sequence([f.permute(0, 2, 1) for f in features], batch_first=True, padding_value=0.0) # (B, C, F, T_max)
    # features_padded = features_padded.permute(0, 1, 3, 2) # (B, C, T_max, F) - Не то

    # Паддим (C, T, F) по оси T (dim=1)
    # Нужно сделать (T, C, F) или (T, F, C) для pad_sequence
    features_padded = pad_sequence([f.permute(1, 0, 2) for f in features], batch_first=False, padding_value=0.0) # (T_max, B, C, F)
    features_padded = features_padded.permute(1, 2, 0, 3) # (B, C, T_max, F) - Вот это должно быть правильно для Conv2d

    # 4. Паддинг текстов (L) -> (B, L_max)
    # Используем blank_idx для паддинга, CTCLoss его игнорирует
    texts_padded = pad_sequence(texts, batch_first=True, padding_value=blank_idx)

    # 5. Стекинг длин
    input_lengths = torch.stack(input_lengths) # Длины исходных признаков (до паддинга)
    target_lengths = torch.stack(target_lengths)

    return features_padded, texts_padded, input_lengths, target_lengths

### Ячейка 8: Определение Модели (Conv2d + BiGRU + CTC)

In [41]:
# Ячейка 8: Определение Модели (Conv2d + BiGRU + CTC)

class MorseRecognizer(nn.Module):
    def __init__(self, config: dict):
        super().__init__()
        audio_cfg = config["audio"]
        model_cfg = config["model"]
        ctc_cfg = config["ctc"]

        n_mels = audio_cfg["n_mels"]
        input_channels = 2 if audio_cfg["use_deltas"] else 1

        # --- CNN Слои ---
        cnn_layers = []
        in_channels = input_channels
        current_freq_dim = n_mels
        self.time_reduction_factor = 1 # Общий фактор сжатия времени

        for i, out_channels in enumerate(model_cfg["cnn_out_channels"]):
            kernel = model_cfg["cnn_kernel_size"][i]
            stride = model_cfg["cnn_stride"][i]
            pool_kernel = model_cfg["cnn_pool_kernel"][i]

            # Добавляем padding='same' для сохранения размерности (кроме stride)
            cnn_layers.append(
                nn.Conv2d(
                    in_channels, out_channels, kernel_size=kernel, stride=stride, padding='same'
                )
            )
            cnn_layers.append(nn.BatchNorm2d(out_channels))
            cnn_layers.append(nn.GELU()) # Используем GELU вместо ReLU

            # Пулинг (сжимаем только время - dim=3, если вход B,C,F,T)
            # В нашем случае вход (B, C, T, F), пулинг по T (dim=2)
            # kernel_size=(pool_kernel[0], pool_kernel[1]) -> (pool_T, pool_F)
            # Нам нужен (pool_T=pool_kernel[1], pool_F=pool_kernel[0]) ???
            # Давайте явно укажем: pool_T = pool_kernel[1], pool_F = pool_kernel[0]
            # Если pool_kernel = (1, 2), то pool_T=2, pool_F=1
            pool_T = pool_kernel[1]
            pool_F = pool_kernel[0]

            cnn_layers.append(
                nn.MaxPool2d(kernel_size=(pool_T, pool_F)) # (pool_T, pool_F)
            )
            in_channels = out_channels
            # Обновляем временной фактор сжатия
            self.time_reduction_factor *= pool_T
            # Обновляем размерность частот после пулинга
            current_freq_dim = current_freq_dim // pool_F


        self.cnn = nn.Sequential(*cnn_layers)

        # --- RNN Слой ---
        # Рассчитываем размер входа для RNN
        # Выход CNN: (B, C_out, T_reduced, F_reduced)
        # Вход RNN: (B, T_reduced, Features) -> Features = C_out * F_reduced
        rnn_input_size = in_channels * current_freq_dim
        self.rnn = nn.GRU(
            input_size=rnn_input_size,
            hidden_size=model_cfg["rnn_hidden_size"],
            num_layers=model_cfg["rnn_layers"],
            batch_first=True, # Ожидаем (B, T, Features)
            bidirectional=True,
            dropout=model_cfg["rnn_dropout"] if model_cfg["rnn_layers"] > 1 else 0.0
        )

        # --- Классификатор ---
        self.dropout = nn.Dropout(model_cfg["dropout"])
        self.classifier = nn.Linear(
            model_cfg["rnn_hidden_size"] * 2, # *2 из-за bidirectional
            model_cfg["vocab_size"]
        )

        print(f"Модель инициализирована. Входные каналы CNN: {input_channels}")
        print(f"Выходные каналы CNN: {in_channels}")
        print(f"Итоговый фактор сжатия времени CNN: {self.time_reduction_factor}")
        print(f"Размерность частот после CNN: {current_freq_dim}")
        print(f"Размер входа RNN: {rnn_input_size}")
        print(f"Размер выхода классификатора: {model_cfg['vocab_size']}")


    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Вход x: (B, C, T, F)
        x = self.cnn(x) # Выход: (B, C_out, T_reduced, F_reduced)

        # Переформатирование для RNN: (B, T_reduced, C_out * F_reduced)
        B, C_out, T_reduced, F_reduced = x.shape
        x = x.permute(0, 2, 1, 3) # (B, T_reduced, C_out, F_reduced)
        x = x.reshape(B, T_reduced, C_out * F_reduced) # (B, T_reduced, Features)

        # RNN
        x, _ = self.rnn(x) # Выход: (B, T_reduced, RNN_hidden * 2)
        x = self.dropout(x)

        # Классификатор
        x = self.classifier(x) # Выход: (B, T_reduced, VocabSize)

        # LogSoftmax НЕ нужен, так как nn.CTCLoss ожидает сырые логиты
        return x

### Ячейка 9: Функции Декодирования и Оценки

In [42]:
# Ячейка 9: Функции Декодирования и Оценки

def ctc_decode_greedy(logits: torch.Tensor, int_to_char: Dict[int, str], blank_idx: int) -> List[str]:
    """Жадное CTC декодирование."""
    # --- УБРАНЫ НЕКОРРЕКТНЫЕ ПРОВЕРКИ GLOBALS ---
    # if 'int_to_char' not in globals() or not int_to_char:
    #     raise ValueError("Словарь int_to_char не определен или пуст! Убедитесь, что Ячейка 4 выполнена.")
    # if 'CONFIG' not in globals() or 'ctc' not in CONFIG or 'blank_idx' not in CONFIG['ctc']:
    #      raise ValueError("CONFIG['ctc']['blank_idx'] не определен! Убедитесь, что Ячейка 2 и 4 выполнены.")
    # blank_idx = CONFIG['ctc']['blank_idx'] # Получаем из аргумента, а не из globals
    # --- КОНЕЦ УДАЛЕНИЯ ---

    # logits: (B, T, V)
    decoded_preds = []
    # Применяем argmax по оси словаря (V)
    best_paths = torch.argmax(logits, dim=2) # (B, T)

    for path in best_paths:
        # 1. Удаляем последовательные дубликаты
        path_no_duplicates = torch.unique_consecutive(path)

        # 2. Удаляем blank токены
        path_no_blanks = [c.item() for c in path_no_duplicates if c.item() != blank_idx]

        # 3. Преобразуем индексы в символы
        # Используем .get(c, '?') для обработки неизвестных индексов, если вдруг появятся
        decoded_text = "".join([int_to_char.get(c, '?') for c in path_no_blanks])
        decoded_preds.append(decoded_text)

    return decoded_preds

def calculate_levenshtein(preds: List[str], targets: List[str]) -> float:
    """Рассчитывает среднее расстояние Левенштейна."""
    total_distance = 0
    count = 0
    for pred, target in zip(preds, targets):
        # Добавим проверку на None или не-строки на всякий случай
        if isinstance(pred, str) and isinstance(target, str):
            total_distance += Levenshtein.distance(pred, target)
            count += 1
        else:
            print(f"Предупреждение: Некорректные типы для Levenshtein: pred='{pred}' ({type(pred)}), target='{target}' ({type(target)})")

    return total_distance / count if count > 0 else 0.0

def decode_targets(targets_padded: torch.Tensor, target_lengths: torch.Tensor, int_to_char: Dict[int, str]) -> List[str]:
    """Декодирует паддированные тензоры целей в строки."""
    # --- УБРАНА НЕКОРРЕКТНАЯ ПРОВЕРКА GLOBALS ---
    # if 'int_to_char' not in globals() or not int_to_char:
    #     raise ValueError("Словарь int_to_char не определен или пуст! Убедитесь, что Ячейка 4 выполнена.")
    # --- КОНЕЦ УДАЛЕНИЯ ---

    decoded_targets = []
    for i in range(targets_padded.size(0)):
        length = target_lengths[i].item()
        # Защита от некорректной длины
        if length <= 0 or length > targets_padded.size(1):
             decoded_targets.append("") # Возвращаем пустую строку для некорректных длин
             continue
        target_indices = targets_padded[i, :length].cpu().numpy()
        # Используем .get(idx, '?') для обработки неизвестных индексов
        decoded_text = "".join([int_to_char.get(idx, '?') for idx in target_indices])
        decoded_targets.append(decoded_text)
    return decoded_targets

### Ячейка 10: Циклы Обучения и Валидации

In [43]:
# Ячейка 10: Циклы Обучения и Валидации

def train_epoch(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    optimizer: optim.Optimizer,
    scheduler: Optional[torch.optim.lr_scheduler._LRScheduler],
    scaler: GradScaler,
    device: torch.device,
    config: dict,
    epoch: int
) -> float:
    """Проводит одну эпоху обучения."""
    model.train()
    total_loss = 0.0
    accum_steps = config["training"]["gradient_accumulation_steps"]
    num_batches = len(loader)
    optimizer.zero_grad() # Очищаем градиенты в начале эпохи / перед первым накоплением

    pbar = tqdm(enumerate(loader), total=num_batches, desc=f"Train Epoch {epoch+1}")
    for i, batch_data in pbar:
        if batch_data is None: # Пропускаем плохие батчи
            print(f"Пропущен пустой батч {i+1}/{num_batches}")
            continue

        features, targets, input_lengths, target_lengths = batch_data
        features = features.to(device)
        targets = targets.to(device)
        input_lengths = input_lengths.to(device) # Не деленные на фактор! CTCLoss ожидает оригинальные
        target_lengths = target_lengths.to(device)

        # --- Automatic Mixed Precision ---
        with autocast(enabled=config["training"]["use_amp"]):
            # Forward pass
            logits = model(features) # (B, T_reduced, V)

            # --- Подготовка для CTCLoss ---
            # CTCLoss ожидает (T, B, V)
            log_probs = logits.log_softmax(dim=2).permute(1, 0, 2) # (T_reduced, B, V)

            # CTCLoss ожидает длины входа ПОСЛЕ CNN/Pooling
            reduced_input_lengths = input_lengths // model.time_reduction_factor
            # Убедимся, что длины не нулевые
            reduced_input_lengths = torch.clamp(reduced_input_lengths, min=1)


            loss = criterion(log_probs, targets, reduced_input_lengths, target_lengths)

            # Масштабирование лосса для накопления градиентов
            loss = loss / accum_steps

        # Backward pass с GradScaler
        scaler.scale(loss).backward()

        # Шаг оптимизатора и обнуление градиентов каждые accum_steps
        if (i + 1) % accum_steps == 0 or (i + 1) == num_batches:
            # Unscale градиенты перед клиппингом
            scaler.unscale_(optimizer)
            # Клиппинг градиентов
            torch.nn.utils.clip_grad_norm_(model.parameters(), config["training"]["gradient_clip_val"])
            # Шаг оптимизатора
            scaler.step(optimizer)
            # Обновление скейлера
            scaler.update()
            # Обнуление градиентов
            optimizer.zero_grad()

            # Обновление LR шедулера (если он не ReduceLROnPlateau)
            if scheduler and not isinstance(scheduler, ReduceLROnPlateau):
                 scheduler.step()


        batch_loss = loss.item() * accum_steps # Возвращаем не масштабированный лосс батча
        total_loss += batch_loss
        pbar.set_postfix(loss=f"{batch_loss:.4f}", lr=f"{optimizer.param_groups[0]['lr']:.2e}")

        # Освобождаем память
        del features, targets, input_lengths, target_lengths, logits, log_probs, loss
        if device == 'cuda': torch.cuda.empty_cache()


    avg_loss = total_loss / num_batches
    return avg_loss


def evaluate(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    device: torch.device,
    config: dict,
    int_to_char: Dict[int, str]
) -> Tuple[float, float]:
    """Проводит оценку на валидационном или тестовом наборе."""
    model.eval()
    total_loss = 0.0
    all_preds = []
    all_targets_decoded = []
    num_batches = len(loader)

    pbar = tqdm(loader, total=num_batches, desc="Validation")
    with torch.no_grad():
        for batch_data in pbar:
            if batch_data is None:
                print(f"Пропущен пустой батч при валидации")
                continue

            features, targets, input_lengths, target_lengths = batch_data
            features = features.to(device)
            targets = targets.to(device)
            input_lengths = input_lengths.to(device)
            target_lengths = target_lengths.to(device)

            # --- Automatic Mixed Precision (для инференса тоже полезно) ---
            with autocast(enabled=config["training"]["use_amp"]):
                logits = model(features) # (B, T_reduced, V)
                log_probs = logits.log_softmax(dim=2).permute(1, 0, 2) # (T_reduced, B, V)
                reduced_input_lengths = torch.clamp(input_lengths // model.time_reduction_factor, min=1)

                loss = criterion(log_probs, targets, reduced_input_lengths, target_lengths)

            total_loss += loss.item()

            # Декодирование предсказаний
            batch_preds = ctc_decode_greedy(logits.cpu(), int_to_char, config["ctc"]["blank_idx"])
            all_preds.extend(batch_preds)

            # Декодирование реальных целей
            batch_targets_decoded = decode_targets(targets.cpu(), target_lengths.cpu(), int_to_char)
            all_targets_decoded.extend(batch_targets_decoded)

            pbar.set_postfix(loss=f"{loss.item():.4f}")

            del features, targets, input_lengths, target_lengths, logits, log_probs, loss
            if device == 'cuda': torch.cuda.empty_cache()


    avg_loss = total_loss / num_batches if num_batches > 0 else 0.0
    avg_levenshtein = calculate_levenshtein(all_preds, all_targets_decoded)

    # Вывод нескольких примеров декодирования
    print("\nПримеры декодирования (Предсказание | Реалность):")
    for i in range(min(5, len(all_preds))):
        print(f"    '{all_preds[i]}' | '{all_targets_decoded[i]}'")

    return avg_loss, avg_levenshtein

### Ячейка 11: Основная функция запуска обучения

In [44]:
# Ячейка 11: Основная функция запуска обучения
import pandas as pd # Убедимся, что pandas импортирован
import numpy as np # Убедимся, что numpy импортирован
import torch # Убедимся, что torch импортирован
from torch.utils.data import random_split # Убедимся, что импортирован
import mlflow # Убедимся, что импортирован
import gc # Убедимся, что импортирован
from pathlib import Path # Убедимся, что импортирован
import time # Убедимся, что импортирован
from torch.optim.lr_scheduler import ReduceLROnPlateau, CosineAnnealingLR # Убедимся, что импортированы
from torch.cuda.amp import GradScaler # Убедимся, что импортирован
import torch.optim as optim # Убедимся, что импортирован
import torch.nn as nn # Убедимся, что импортирован
from torch.utils.data import DataLoader # Убедимся, что импортирован


def run_training_pipeline(config: dict, train_df: pd.DataFrame, char_to_int: dict, int_to_char: dict,
                           feature_mean: np.ndarray, feature_std: np.ndarray) -> str:
    """Запускает полный цикл обучения и валидации."""

    device = torch.device(config["training"]["device"])
    output_dir = Path(config["paths"]["output_dir"])
    run_name = f"{config['mlflow']['run_name_prefix']}_{time.strftime('%Y%m%d_%H%M%S')}"
    text_column_name = 'message' # Имя столбца с текстом

    # Инициализируем переменные до блока try, чтобы они были доступны в finally
    model = None
    optimizer = None
    criterion = None
    scaler = None
    scheduler = None
    train_loader = None
    val_loader = None
    train_ds = None
    val_ds = None
    best_model_path = "" # Инициализируем пустой строкой
    active_mlflow_run = False # Флаг для проверки активного MLflow run

    try: # Добавляем try..except вокруг всего основного кода функции
        with mlflow.start_run(run_name=run_name) as run:
            active_mlflow_run = True # Устанавливаем флаг, что run начался
            print(f"MLflow Run ID: {run.info.run_id}")
            # Логирование конфигурации
            config_save_path = output_dir / "config.json" # Путь к сохраненному конфигу
            if config_save_path.exists():
                 mlflow.log_artifact(str(config_save_path))
            else:
                 mlflow.log_dict(config, "config.json")

            # Логируем параметры, проверяя на None
            flat_config = pd.json_normalize(config, sep='.').to_dict(orient='records')[0]
            mlflow.log_params({k: v for k, v in flat_config.items() if v is not None})
            mlflow.log_param("mlflow_run_id", run.info.run_id)

            # --- Подготовка данных ---
            print("Подготовка подвыборки данных...")
            if config["mode"]["calibration_mode"]:
                subset_size = config["mode"]["calibration_subset_size"]
                if subset_size < len(train_df):
                    train_indices = np.random.choice(train_df.index, subset_size, replace=False)
                    train_subset_df = train_df.loc[train_indices].copy()
                    print(f"Используется калибровочная подвыборка из {subset_size} записей.")
                else:
                    train_subset_df = train_df.copy()
                    print(f"Размер калибровочной выборки ({subset_size}) >= размеру датасета ({len(train_df)}). Используются все данные.")
            else:
                train_subset_df = train_df.copy()

            # Сбросим индекс у подвыборки, чтобы использовать .iloc надежно
            train_subset_df = train_subset_df.reset_index(drop=True)
            print(f"Размер подготовленной подвыборки (train_subset_df): {len(train_subset_df)}")
            if len(train_subset_df) == 0:
                raise ValueError("Подвыборка данных (train_subset_df) оказалась пустой!")


            # Разделение на train/validation
            print("Разделение данных на train/validation...")
            val_size = int(len(train_subset_df) * config["training"]["val_split_ratio"])
            train_size = len(train_subset_df) - val_size
            print(f"Размеры: Train={train_size}, Validation={val_size}")

            if val_size <= 0 or train_size <= 0:
                 raise ValueError(f"Некорректные размеры train ({train_size}) / val ({val_size}) split. Проверьте val_split_ratio и размер данных.")

            # --- ИЗМЕНЕНИЕ ЗДЕСЬ: Правильное извлечение индексов ---
            # 1. Создаем последовательность для разделения (0, 1, ..., N-1)
            num_samples_to_split = len(train_subset_df)
            indices_sequence = list(range(num_samples_to_split))

            # 2. Разделяем эту последовательность
            train_pos_subset, val_pos_subset = random_split(
                indices_sequence, [train_size, val_size],
                generator=torch.Generator().manual_seed(config["random_seed"])
            )

            # 3. Извлекаем списки целочисленных позиций из атрибута .indices
            train_iloc_indices = train_pos_subset.indices # <-- ИЗВЛЕКАЕМ .indices
            val_iloc_indices = val_pos_subset.indices   # <-- ИЗВЛЕКАЕМ .indices

            # --- Отладочная печать ---
            print(f"Тип train_iloc_indices: {type(train_iloc_indices)}, Длина: {len(train_iloc_indices)}")
            print(f"Первые 5 train_iloc_indices: {train_iloc_indices[:5]}")
            print(f"Тип val_iloc_indices: {type(val_iloc_indices)}, Длина: {len(val_iloc_indices)}")
            print(f"Первые 5 val_iloc_indices: {val_iloc_indices[:5]}")
            # --- Конец отладочной печати ---

            # 4. Используем .iloc с этими позициями для создания датасетов
            print("Создание Train Dataset...")
            train_ds = MorseDataset(
                train_subset_df.iloc[train_iloc_indices], # Используем .iloc с списком индексов
                char_to_int, config["audio"], config["augmentation"],
                text_column=text_column_name,
                feature_mean=feature_mean, feature_std=feature_std,
                augment=config["augmentation"]["apply_augmentations"]
            )
            print("Создание Validation Dataset...")
            val_ds = MorseDataset(
                train_subset_df.iloc[val_iloc_indices], # Используем .iloc с списком индексов
                char_to_int, config["audio"], config["augmentation"],
                text_column=text_column_name,
                feature_mean=feature_mean, feature_std=feature_std,
                augment=False
            )
            # --- КОНЕЦ ИЗМЕНЕНИЯ ---

            # Создание DataLoader'ов
            print("Создание DataLoader'ов...")
            collate_wrapper = lambda batch: collate_fn(batch, config["ctc"]["blank_idx"])
            train_loader = DataLoader(
                train_ds, batch_size=config["training"]["batch_size"], shuffle=True,
                num_workers=config["training"]["num_workers"], collate_fn=collate_wrapper, pin_memory=True,
                persistent_workers=True if config["training"]["num_workers"] > 0 else False,
                prefetch_factor=2 if config["training"]["num_workers"] > 0 else None,
                drop_last=True
            )
            val_loader = DataLoader(
                val_ds, batch_size=config["training"]["batch_size"] * 2, shuffle=False,
                num_workers=config["training"]["num_workers"], collate_fn=collate_wrapper, pin_memory=True,
                persistent_workers=True if config["training"]["num_workers"] > 0 else False,
                prefetch_factor=2 if config["training"]["num_workers"] > 0 else None
            )
            print(f"Размер Train Dataset: {len(train_ds)}, Val Dataset: {len(val_ds)}")
            print(f"Train Batches: {len(train_loader)}, Val Batches: {len(val_loader)}")
            if len(train_loader) == 0 or len(val_loader) == 0:
                 raise ValueError("Один из DataLoader'ов пуст! Проверьте размеры данных и batch_size.")


            # --- Инициализация модели, оптимизатора, лосса, скейлера ---
            print("Инициализация модели и компонентов обучения...")
            model = MorseRecognizer(config).to(device)
            criterion = nn.CTCLoss(blank=config["ctc"]["blank_idx"], reduction='mean', zero_infinity=True)

            if config["training"]["optimizer"].lower() == "adamw":
                optimizer = optim.AdamW(model.parameters(), lr=config["training"]["learning_rate"],
                                       weight_decay=config["training"]["weight_decay"])
            else: # По умолчанию Adam
                 optimizer = optim.Adam(model.parameters(), lr=config["training"]["learning_rate"],
                                       weight_decay=config["training"]["weight_decay"])

            scaler = GradScaler(enabled=config["training"]["use_amp"])

            # Инициализация LR шедулера
            scheduler = None
            scheduler_name = config["training"]["scheduler"].lower()
            steps_per_epoch = len(train_loader) # len(train_loader) уже учитывает drop_last
            if config["training"]["gradient_accumulation_steps"] > 1:
                 steps_per_epoch = steps_per_epoch // config["training"]["gradient_accumulation_steps"]
            if steps_per_epoch == 0: steps_per_epoch = 1
            total_steps = config["training"]["epochs"] * steps_per_epoch
            print(f"Расчетное количество шагов оптимизатора за эпоху: {steps_per_epoch}")
            print(f"Общее количество шагов для CosineAnnealingLR: {total_steps}")


            if scheduler_name == "reducelronplateau":
                scheduler = ReduceLROnPlateau(
                    optimizer, mode='min', factor=config["training"]["lr_scheduler_factor"],
                    patience=config["training"]["lr_scheduler_patience"], verbose=True, min_lr=config["training"]["lr_min"]
                )
                print("Используется ReduceLROnPlateau scheduler.")
            elif scheduler_name == "cosineannealinglr":
                 scheduler = CosineAnnealingLR(
                    optimizer, T_max=total_steps,
                    eta_min=config["training"]["lr_min"]
                )
                 print("Используется CosineAnnealingLR scheduler.")
            else:
                 print("LR scheduler не используется.")


            # --- Цикл обучения ---
            print("Начало цикла обучения...")
            best_val_levenshtein = float('inf')
            epochs_no_improve = 0
            # best_model_path инициализирован выше

            for epoch in range(config["training"]["epochs"]):
                print("-" * 30)
                start_time = time.time()

                # Обучение
                train_loss = train_epoch(model, train_loader, criterion, optimizer, scheduler, scaler, device, config, epoch)

                # Валидация
                val_loss, val_levenshtein = evaluate(model, val_loader, criterion, device, config, int_to_char)

                end_time = time.time()
                epoch_duration = end_time - start_time

                print(f"\nEpoch {epoch+1}/{config['training']['epochs']} Summary:")
                print(f"  Train Loss: {train_loss:.4f}")
                print(f"  Val Loss:   {val_loss:.4f}")
                print(f"  Val Levenshtein: {val_levenshtein:.4f} (Best: {best_val_levenshtein:.4f})")
                print(f"  Epoch Duration: {epoch_duration:.2f} sec")
                print(f"  Learning Rate: {optimizer.param_groups[0]['lr']:.2e}")

                # Логирование метрик в MLflow
                mlflow.log_metric("train_loss", train_loss, step=epoch)
                mlflow.log_metric("val_loss", val_loss, step=epoch)
                mlflow.log_metric("val_levenshtein", val_levenshtein, step=epoch)
                mlflow.log_metric("learning_rate", optimizer.param_groups[0]['lr'], step=epoch)


                # Обновление LR шедулера (если ReduceLROnPlateau)
                if scheduler and isinstance(scheduler, ReduceLROnPlateau):
                     scheduler.step(val_levenshtein)
                # Для CosineAnnealingLR шаг делается внутри train_epoch


                # Сохранение лучшей модели и Early Stopping
                if val_levenshtein < best_val_levenshtein:
                    best_val_levenshtein = val_levenshtein
                    epochs_no_improve = 0
                    safe_run_name = run_name.replace(":", "-").replace(" ", "_")
                    model_save_path = output_dir / f"{safe_run_name}_best_model_epoch{epoch+1}_lev{val_levenshtein:.4f}.pth"
                    torch.save(model.state_dict(), model_save_path)
                    best_model_path = str(model_save_path)
                    print(f"  ✨ New best model saved to {model_save_path}")
                    mlflow.log_metric("best_val_levenshtein", best_val_levenshtein, step=epoch)
                else:
                    epochs_no_improve += 1
                    print(f"  Validation Levenshtein не улучшился. Счетчик: {epochs_no_improve}/{config['training']['early_stopping_patience']}")

                if epochs_no_improve >= config["training"]["early_stopping_patience"]:
                    print(f"\n❗️ Early stopping triggered after {epoch + 1} epochs.")
                    break

                # Очистка памяти после эпохи
                gc.collect()
                if device == 'cuda': torch.cuda.empty_cache()

            print("\nОбучение завершено.")
            if best_model_path:
                print(f"Лучшая модель сохранена в: {best_model_path}")
                mlflow.log_artifact(best_model_path, artifact_path="best_model")
            else:
                print("Лучшая модель не была сохранена.")

            mlflow.log_metric("final_best_val_levenshtein", best_val_levenshtein)
            # Завершаем MLflow run успешно
            mlflow.end_run(status="FINISHED")
            active_mlflow_run = False


    except Exception as e: # Ловим исключение здесь
         print(f"\n❌ Ошибка во время выполнения конвейера обучения:")
         import traceback
         traceback.print_exc()
         # Завершаем run в MLflow с ошибкой, если он был начат
         if active_mlflow_run: # Используем флаг
             try:
                 mlflow.end_run(status="FAILED")
             except Exception as mlflow_err:
                 print(f"Ошибка при завершении MLflow run: {mlflow_err}")
         # Пробрасываем исключение дальше, чтобы ячейка завершилась с ошибкой
         raise e

    # Блок finally будет выполнен всегда
    finally:
        # --- БЛОК FINALLY ---
        print("\nОчистка ресурсов...")
        # Проверяем каждую переменную перед удалением
        if 'model' in locals() and model is not None:
            del model
        if 'optimizer' in locals() and optimizer is not None:
            del optimizer
        if 'criterion' in locals() and criterion is not None:
            del criterion
        if 'scaler' in locals() and scaler is not None:
            del scaler
        if 'scheduler' in locals() and scheduler is not None:
            del scheduler
        if 'train_loader' in locals() and train_loader is not None:
            del train_loader
        if 'val_loader' in locals() and val_loader is not None:
            del val_loader
        if 'train_ds' in locals() and train_ds is not None:
            del train_ds
        if 'val_ds' in locals() and val_ds is not None:
            del val_ds

        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        print("Очистка завершена.")
        # --- КОНЕЦ БЛОКА FINALLY ---


    return best_model_path # Возвращаем путь к лучшей модели

### Ячейка 12: Запуск Конвейера Обучения

In [ ]:
# Ячейка 12: Запуск Конвейера Обучения

# Убедитесь, что CONFIG настроен правильно (особенно calibration_mode)
print(f"Запуск обучения в режиме: {'Калибровка' if CONFIG['mode']['calibration_mode'] else 'Полное обучение'}")
print(f"Используется устройство: {CONFIG['training']['device']}")

# Запуск
try:
    best_model_file = run_training_pipeline(
        CONFIG,
        train_df,
        char_to_int,
        int_to_char,
        feature_mean,
        feature_std
    )
    print(f"\n✅ Конвейер обучения успешно завершен. Лучшая модель: {best_model_file}")

    # --- Добавляем путь к лучшей модели в конфиг для инференса ---
    CONFIG["inference"] = {"best_model_path": best_model_file}
    # Обновляем сохраненный config.json
    config_save_path = Path(CONFIG["paths"]["output_dir"]) / "config.json"
    with open(config_save_path, 'w') as f:
        json.dump(CONFIG, f, indent=4)
    print(f"Путь к лучшей модели добавлен в {config_save_path}")


except Exception as e:
    print(f"\n❌ Ошибка во время выполнения конвейера обучения:")
    import traceback
    traceback.print_exc()
    # Завершаем run в MLflow с ошибкой
    mlflow.end_run(status="FAILED")

finally:
    # Очистка памяти GPU
    del model, optimizer, criterion, scaler, scheduler, train_loader, val_loader, train_ds, val_ds
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

Запуск обучения в режиме: Полное обучение
Используется устройство: cuda
MLflow Run ID: b8a37d42a4664b25a5e4c314fb4426a2
Подготовка подвыборки данных...
Размер подготовленной подвыборки (train_subset_df): 30000
Разделение данных на train/validation...
Размеры: Train=27000, Validation=3000
Тип train_iloc_indices: <class 'list'>, Длина: 27000
Первые 5 train_iloc_indices: [7542, 10109, 19114, 5209, 9270]
Тип val_iloc_indices: <class 'list'>, Длина: 3000
Первые 5 val_iloc_indices: [16386, 16481, 11686, 18711, 13975]
Создание Train Dataset...
Создание Validation Dataset...
Создание DataLoader'ов...
Размер Train Dataset: 27000, Val Dataset: 3000
Train Batches: 1687, Val Batches: 94
Инициализация модели и компонентов обучения...
Модель инициализирована. Входные каналы CNN: 1
Выходные каналы CNN: 64
Итоговый фактор сжатия времени CNN: 4
Размерность частот после CNN: 32
Размер входа RNN: 2048
Размер выхода классификатора: 45
Расчетное количество шагов оптимизатора за эпоху: 1687
Общее количество шагов для CosineAnnealingLR: 84350
Используется ReduceLROnPlateau scheduler.
Начало цикла обучения...
------------------------------

Train Epoch 1:   0%|          | 0/1687 [00:00<?, ?it/s]

Validation:   0%|          | 0/94 [00:00<?, ?it/s]

Примеры декодирования (Предсказание | Реалность):
    'Ы' | 'ФААР834ОМП'
    '' | 'Т0С ЖЩ0О БМЫ'
    'Ы' | 'ЬЛННЖЗУЯН3ЭХ7'
    'Э' | 'АИИ9Ъ9ОЭЯЕ'
    '' | '#6ЧФ8ЮО'

Epoch 1/50 Summary:
  Train Loss: 4.2111
  Val Loss:   3.9948
  Val Levenshtein: 8.7647 (Best: inf)
  Epoch Duration: 907.52 sec
  Learning Rate: 3.00e-04
  ✨ New best model saved to output\morse_exp_20250414_135549_best_model_epoch1_lev8.7647.pth
------------------------------

Train Epoch 2:   0%|          | 0/1687 [00:00<?, ?it/s]

Validation:   0%|          | 0/94 [00:00<?, ?it/s]

Примеры декодирования (Предсказание | Реалность):
    '3Ш' | 'ФААР834ОМП'
    '3 Ш' | 'Т0С ЖЩ0О БМЫ'
    '3Ш' | 'ЬЛННЖЗУЯН3ЭХ7'
    '3Ш' | 'АИИ9Ъ9ОЭЯЕ'
    'ЙШ' | '#6ЧФ8ЮО'

Epoch 2/50 Summary:
  Train Loss: 3.9839
  Val Loss:   3.9551
  Val Levenshtein: 8.3103 (Best: 8.7647)
  Epoch Duration: 684.58 sec
  Learning Rate: 3.00e-04
  ✨ New best model saved to output\morse_exp_20250414_135549_best_model_epoch2_lev8.3103.pth
------------------------------

Train Epoch 3:   0%|          | 0/1687 [00:00<?, ?it/s]

Validation:   0%|          | 0/94 [00:00<?, ?it/s]

Примеры декодирования (Предсказание | Реалность):
    'РАРР833МГ' | 'ФААР834ОМП'
    'МС ЖЩ0Ч БМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХ7' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИЧЪЧОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#БЧФ8ЮО' | '#6ЧФ8ЮО'

Epoch 3/50 Summary:
  Train Loss: 3.5209
  Val Loss:   0.9902
  Val Levenshtein: 1.9973 (Best: 8.3103)
  Epoch Duration: 519.84 sec
  Learning Rate: 3.00e-04
  ✨ New best model saved to output\morse_exp_20250414_135549_best_model_epoch3_lev1.9973.pth
------------------------------

Train Epoch 4:   0%|          | 0/1687 [00:00<?, ?it/s]

Validation:   0%|          | 0/94 [00:00<?, ?it/s]

Примеры декодирования (Предсказание | Реалность):
    'РААР834ОМП' | 'ФААР834ОМП'
    'ТШОС ЖЩ08 БМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХ7' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#6ЧФ8ЮО' | '#6ЧФ8ЮО'

Epoch 4/50 Summary:
  Train Loss: 0.9822
  Val Loss:   0.3382
  Val Levenshtein: 0.7220 (Best: 1.9973)
  Epoch Duration: 518.05 sec
  Learning Rate: 3.00e-04
  ✨ New best model saved to output\morse_exp_20250414_135549_best_model_epoch4_lev0.7220.pth
------------------------------

Train Epoch 5:   0%|          | 0/1687 [00:00<?, ?it/s]

Validation:   0%|          | 0/94 [00:00<?, ?it/s]

Примеры декодирования (Предсказание | Реалность):
    'ФААР834ОМП' | 'ФААР834ОМП'
    'Т0С ЖЩ0О БМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХ7' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#6ЧФ8ЮО' | '#6ЧФ8ЮО'

Epoch 5/50 Summary:
  Train Loss: 0.7551
  Val Loss:   0.2822
  Val Levenshtein: 0.6213 (Best: 0.7220)
  Epoch Duration: 521.76 sec
  Learning Rate: 3.00e-04
  ✨ New best model saved to output\morse_exp_20250414_135549_best_model_epoch5_lev0.6213.pth
------------------------------

Train Epoch 6:   0%|          | 0/1687 [00:00<?, ?it/s]

Validation:   0%|          | 0/94 [00:00<?, ?it/s]

Примеры декодирования (Предсказание | Реалность):
    'ФААР834ОМП' | 'ФААР834ОМП'
    'Т9ОС ЖЩ08 БМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХ7' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#6ЧФ8ЮО' | '#6ЧФ8ЮО'

Epoch 6/50 Summary:
  Train Loss: 0.6997
  Val Loss:   0.2607
  Val Levenshtein: 0.5803 (Best: 0.6213)
  Epoch Duration: 515.09 sec
  Learning Rate: 3.00e-04
  ✨ New best model saved to output\morse_exp_20250414_135549_best_model_epoch6_lev0.5803.pth
------------------------------

Train Epoch 7:   0%|          | 0/1687 [00:00<?, ?it/s]

Validation:   0%|          | 0/94 [00:00<?, ?it/s]

Примеры декодирования (Предсказание | Реалность):
    'ФААР834ОМП' | 'ФААР834ОМП'
    'Т0ОС ЖЩ0З БМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХ7' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#6ЧФ8ЮО' | '#6ЧФ8ЮО'

Epoch 7/50 Summary:
  Train Loss: 0.5904
  Val Loss:   0.2381
  Val Levenshtein: 0.5587 (Best: 0.5803)
  Epoch Duration: 510.61 sec
  Learning Rate: 3.00e-04
  ✨ New best model saved to output\morse_exp_20250414_135549_best_model_epoch7_lev0.5587.pth
------------------------------

Train Epoch 8:   0%|          | 0/1687 [00:00<?, ?it/s]

Validation:   0%|          | 0/94 [00:00<?, ?it/s]

Примеры декодирования (Предсказание | Реалность):
    'ФААР834ОМП' | 'ФААР834ОМП'
    'Т0ОС ЖЩ0З БМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХ7' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#6ЧФ8ЮО' | '#6ЧФ8ЮО'

Epoch 8/50 Summary:
  Train Loss: 0.4752
  Val Loss:   0.2275
  Val Levenshtein: 0.5083 (Best: 0.5587)
  Epoch Duration: 521.27 sec
  Learning Rate: 3.00e-04
  ✨ New best model saved to output\morse_exp_20250414_135549_best_model_epoch8_lev0.5083.pth
------------------------------

Train Epoch 9:   0%|          | 0/1687 [00:00<?, ?it/s]

Validation:   0%|          | 0/94 [00:00<?, ?it/s]

Примеры декодирования (Предсказание | Реалность):
    'ФААР834ОМП' | 'ФААР834ОМП'
    'Т0С ЖЩ0З БМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХ7' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#6ЧФ8ЮО' | '#6ЧФ8ЮО'

Epoch 9/50 Summary:
  Train Loss: 0.4009
  Val Loss:   0.2277
  Val Levenshtein: 0.5153 (Best: 0.5083)
  Epoch Duration: 517.43 sec
  Learning Rate: 3.00e-04
  Validation Levenshtein не улучшился. Счетчик: 1/10
------------------------------

Train Epoch 10:   0%|          | 0/1687 [00:00<?, ?it/s]

Validation:   0%|          | 0/94 [00:00<?, ?it/s]

Примеры декодирования (Предсказание | Реалность):
    'ФААР834ОМП' | 'ФААР834ОМП'
    'ТНОС ЖЩ0З БМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХ7' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#6ЧФ8ЮО' | '#6ЧФ8ЮО'

Epoch 10/50 Summary:
  Train Loss: 0.3673
  Val Loss:   0.2248
  Val Levenshtein: 0.5053 (Best: 0.5083)
  Epoch Duration: 518.02 sec
  Learning Rate: 3.00e-04
  ✨ New best model saved to output\morse_exp_20250414_135549_best_model_epoch10_lev0.5053.pth
------------------------------

Train Epoch 11:   0%|          | 0/1687 [00:00<?, ?it/s]

Validation:   0%|          | 0/94 [00:00<?, ?it/s]

Примеры декодирования (Предсказание | Реалность):
    'ФААР834ОМП' | 'ФААР834ОМП'
    'ТОС ЖЩ0З БМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХ7' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#6ЧФ8ЮО' | '#6ЧФ8ЮО'

Epoch 11/50 Summary:
  Train Loss: 0.3444
  Val Loss:   0.2135
  Val Levenshtein: 0.4747 (Best: 0.5053)
  Epoch Duration: 517.65 sec
  Learning Rate: 3.00e-04
  ✨ New best model saved to output\morse_exp_20250414_135549_best_model_epoch11_lev0.4747.pth
------------------------------

Train Epoch 12:   0%|          | 0/1687 [00:00<?, ?it/s]

Validation:   0%|          | 0/94 [00:00<?, ?it/s]

Примеры декодирования (Предсказание | Реалность):
    'ФААР834ОМЪ' | 'ФААР834ОМП'
    'ТНОС ЖЩ0О БМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХ7' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#6ЧФ8ЮО' | '#6ЧФ8ЮО'

Epoch 12/50 Summary:
  Train Loss: 0.3202
  Val Loss:   0.2181
  Val Levenshtein: 0.4853 (Best: 0.4747)
  Epoch Duration: 519.40 sec
  Learning Rate: 3.00e-04
  Validation Levenshtein не улучшился. Счетчик: 1/10
------------------------------

Train Epoch 13:   0%|          | 0/1687 [00:00<?, ?it/s]

### Ячейка 13: Инференс и Создание Submission Файла (Опционально)

In [ ]:
# Ячейка 13: Инференс и Создание Submission Файла (Опционально)

def generate_submission(config: dict, test_df: pd.DataFrame, int_to_char: dict,
                        feature_mean: np.ndarray, feature_std: np.ndarray):
    """Генерирует предсказания для тестового набора и создает submission файл."""

    print("\n--- Генерация Submission ---")
    device = torch.device(config["training"]["device"])
    output_dir = Path(config["paths"]["output_dir"])

    # --- Загрузка лучшей модели ---
    model_path = config.get("inference", {}).get("best_model_path")
    if not model_path or not Path(model_path).exists():
        print("❌ Путь к лучшей модели не найден в конфигурации или файл не существует. Инференс невозможен.")
        return

    print(f"Загрузка лучшей модели из: {model_path}")
    model = MorseRecognizer(config).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    # --- Подготовка тестовых данных ---
    # Используем те же параметры, но БЕЗ аугментаций
    test_ds = MorseDataset(
        test_df, char_to_int, config["audio"], config["augmentation"],
        feature_mean, feature_std, augment=False # НИКАКИХ аугментаций на тесте!
    )
    collate_wrapper = lambda batch: collate_fn(batch, config["ctc"]["blank_idx"])
    test_loader = DataLoader(
        test_ds, batch_size=config["training"]["batch_size"] * 2, # Можно увеличить батч для инференса
        shuffle=False, num_workers=config["training"]["num_workers"],
        collate_fn=collate_wrapper, pin_memory=True
    )
    print(f"Размер Test Dataset: {len(test_ds)}, Test Batches: {len(test_loader)}")


    # --- Инференс ---
    predictions = {} # Словарь {file_path: morse_code}
    file_paths_in_loader_order = [] # Сохраняем порядок файлов из loader'а

    # Получаем порядок файлов из test_ds (DataLoader может его менять, если shuffle=True, но у нас False)
    # Однако, лучше явно сохранить порядок из оригинального test_df
    original_file_order = test_df['file_path'].tolist()


    with torch.no_grad():
        pbar = tqdm(test_loader, desc="Инференс")
        batch_idx = 0
        for batch_data in pbar:
            if batch_data is None:
                print(f"Пропущен пустой батч при инференсе")
                # Нужно как-то обработать пропущенные файлы, если они есть
                # Пока просто пропускаем батч
                start_idx = batch_idx * test_loader.batch_size
                end_idx = start_idx + test_loader.batch_size # Приблизительно
                print(f"ВНИМАНИЕ: Пропущен батч {batch_idx+1}. Файлы с индексами ~{start_idx}-{end_idx} могут отсутствовать.")
                batch_idx += 1
                continue

            features, _, input_lengths, _ = batch_data # Нам не нужны targets на тесте
            features = features.to(device)

            # Определяем file_path для текущего батча
            start_idx = batch_idx * test_loader.batch_size
            end_idx = start_idx + features.size(0) # Реальный размер батча
            current_batch_files = original_file_order[start_idx:end_idx]


            with autocast(enabled=config["training"]["use_amp"]):
                logits = model(features) # (B, T_reduced, V)

            # Декодирование
            batch_preds = ctc_decode_greedy(logits.cpu(), int_to_char, config["ctc"]["blank_idx"])

            # Сохранение предсказаний
            for file_p, pred in zip(current_batch_files, batch_preds):
                 predictions[file_p] = pred

            batch_idx += 1

            del features, input_lengths, logits
            if device == 'cuda': torch.cuda.empty_cache()


    # --- Формирование Submission файла ---
    # Убедимся, что все файлы из test_df есть в predictions
    submission_rows = []
    missing_files = 0
    for file_p in original_file_order:
        pred = predictions.get(file_p)
        if pred is None:
            print(f"⚠️ ВНИМАНИЕ: Предсказание для файла {file_p} отсутствует! Заполняем пустой строкой.")
            pred = "" # Или другое значение по умолчанию
            missing_files += 1
        submission_rows.append({"file_path": file_p, "morse_code": pred})

    if missing_files > 0:
         print(f"Количество отсутствующих предсказаний: {missing_files}")


    submission_df = pd.DataFrame(submission_rows)
    submission_path = output_dir / f"{run_name}_submission.csv"
    submission_df.to_csv(submission_path, index=False)
    print(f"Submission файл сохранен в: {submission_path}")

    # Логирование submission файла в MLflow
    try:
        mlflow.log_artifact(str(submission_path))
        print("Submission файл залогирован в MLflow.")
    except Exception as e:
        print(f"Не удалось залогировать submission файл в MLflow: {e}")


# --- Запуск генерации submission (если обучение прошло успешно) ---
if 'inference' in CONFIG and CONFIG['inference'].get('best_model_path'):
    generate_submission(CONFIG, test_df, int_to_char, feature_mean, feature_std)
else:
    print("\nИнференс не запущен, так как нет информации о лучшей модели в CONFIG.")

--- Ячейка 13 (v13.0 - Исправлено): Запуск Обучения (Raw Audio - Оригинал) ---

1. Подготовка конфигурации для ЗАПУСКА ОБУЧЕНИЯ RAW AUDIO (Оригинал)...
  Запускаемая конфигурация: 'RawAudio_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1'
  Batch Size: 8

--- Начало ОБУЧЕНИЯ RAW AUDIO (RawAudio_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1) ---
MLflow эксперимент: 'Morse_RawAudio_v13'

--- Попытка завершить активный MLflow run ---
--- Активный MLflow run не обнаружен или завершен. ---
Очистка памяти перед запуском...
--- Вызов run_training_pipeline_raw для 'RawAudio_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1' ---

==================== Запуск Raw Audio: RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1 ====================
--- Используемые Конфигурации ---
Model Config (Raw): {"initial_out_channels": 64, "initial_kernel_size": 257, "initial_stride": 16, "cnn_block_channels": [128, 128, 128], "cnn_block_kernels": [33, 33, 33], "cnn_use_pooling": [true, true, false], "rnn_hidden_size": 256, "rnn_num_layers": 2, "dropout_rate": 0.2, "activation_fn": "GELU"}
Train Config (Raw): {"batch_size": 8, "num_workers": 0, "num_epochs": 60, "learning_rate": 0.0001, "optimizer": "AdamW", "weight_decay": 0.0001, "div_factor": 10.0, "final_div_factor": 10000.0, "onecycle_pct_start": 0.3, "early_stopping_patience": 15, "gradient_clip_norm": 1.0, "validation_split_ratio": 0.1, "base_seed": 42, "batches_per_epoch": 0}
---------------------------------
  Пути вывода: Model=model_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.pth, Params=params_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.json, Sub=submission_greedy_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.csv
Установлен SEED = 42

1. Подготовка данных (Raw Audio)...
MorseDatasetRaw (v13.0): is_test_set=False, SR=8000Hz, Trimming OFF
  Признаки: Raw Audio -> Tensor(1, T_raw)
MorseDatasetRaw (v13.0): is_test_set=False, SR=8000Hz, Trimming OFF
  Признаки: Raw Audio -> Tensor(1, T_raw)
  Данные готовы: Train=27000 (3375 батчей), Val=3000 (188 батчей). BS=8.

2. Инициализация компонентов...
Инициализация Input Conv: k=257, s=16, out_ch=64
Инициализация 3 CNN блоков...
  Блок 1: in=64, out=128, k=33, pool=True
  Блок 2: in=128, out=128, k=33, pool=True
  Блок 3: in=128, out=128, k=33, pool=False
  Выходная размерность CNN: 128
Инициализация RNN: BiGRU, 2 слоя, hidden=256
Инициализация Classifier: 512 -> 45

Модель RawMorseRecognizer (v13.0) инициализирована.
  Ожидаемый фактор редукции времени: ~x64
  Оптимизатор: AdamW
  INFO: Используется полная длина эпохи: 3375 шагов
  DEBUG: OneCycleLR total_steps РАССЧИТАН КАК: 202500
  Планировщик: OneCycleLR (total_steps=202500, div_factor=10.0)

3. Запуск цикла (Training_RawAudio_from_Scratch)...
--- Эпоха 1/60 ---

Эпоха 1/60 [Тренировка]:   0%|                                                                                …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 1: Train Loss=14.1657, Train Lev=9.3874, Val Loss=4.0428, Val Lev=8.8780
  Примеры декодирования (Предсказание | Реалность):
    '' | 'ФААР834ОМП'
    '' | 'Т0С ЖЩ0О БМЫ'
    '' | 'ЬЛННЖЗУЯН3ЭХ7'
    '' | 'АИИ9Ъ9ОЭЯЕ'
    '' | '#6ЧФ8ЮО'
    '' | 'ЫЭ# НЬЦЦ'
    '' | '8ЖЭК ЛТЕ'
    '' | '5О4ГЪЦ'
    '' | 'ДФЯЯХЭФ9'
    '' | 'ЧШ9А 8П'
  ✨ Val Lev улучшился: inf -> 8.8780. Сохранение модели...
    Модель сохранена: model_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.pth
--- Эпоха 2/60 ---

Эпоха 2/60 [Тренировка]:   0%|                                                                                …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 2: Train Loss=4.0147, Train Lev=8.9211, Val Loss=4.0333, Val Lev=8.8780
  Примеры декодирования (Предсказание | Реалность):
    '' | 'ФААР834ОМП'
    '' | 'Т0С ЖЩ0О БМЫ'
    '' | 'ЬЛННЖЗУЯН3ЭХ7'
    '' | 'АИИ9Ъ9ОЭЯЕ'
    '' | '#6ЧФ8ЮО'
    '' | 'ЫЭ# НЬЦЦ'
    '' | '8ЖЭК ЛТЕ'
    '' | '5О4ГЪЦ'
    '' | 'ДФЯЯХЭФ9'
    '' | 'ЧШ9А 8П'
  Val Lev не улучшился (8.8780 vs best 8.8780). Без улучшений: 1/15
--- Эпоха 3/60 ---

Эпоха 3/60 [Тренировка]:   0%|                                                                                …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 3: Train Loss=4.0088, Train Lev=8.9211, Val Loss=4.0181, Val Lev=8.8780
  Примеры декодирования (Предсказание | Реалность):
    '' | 'ФААР834ОМП'
    '' | 'Т0С ЖЩ0О БМЫ'
    '' | 'ЬЛННЖЗУЯН3ЭХ7'
    '' | 'АИИ9Ъ9ОЭЯЕ'
    '' | '#6ЧФ8ЮО'
    '' | 'ЫЭ# НЬЦЦ'
    '' | '8ЖЭК ЛТЕ'
    '' | '5О4ГЪЦ'
    '' | 'ДФЯЯХЭФ9'
    '' | 'ЧШ9А 8П'
  Val Lev не улучшился (8.8780 vs best 8.8780). Без улучшений: 2/15
--- Эпоха 4/60 ---

Эпоха 4/60 [Тренировка]:   0%|                                                                                …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 4: Train Loss=4.0002, Train Lev=8.9211, Val Loss=4.0026, Val Lev=8.8780
  Примеры декодирования (Предсказание | Реалность):
    '' | 'ФААР834ОМП'
    '' | 'Т0С ЖЩ0О БМЫ'
    '' | 'ЬЛННЖЗУЯН3ЭХ7'
    '' | 'АИИ9Ъ9ОЭЯЕ'
    '' | '#6ЧФ8ЮО'
    '' | 'ЫЭ# НЬЦЦ'
    '' | '8ЖЭК ЛТЕ'
    '' | '5О4ГЪЦ'
    '' | 'ДФЯЯХЭФ9'
    '' | 'ЧШ9А 8П'
  Val Lev не улучшился (8.8780 vs best 8.8780). Без улучшений: 3/15
--- Эпоха 5/60 ---

Эпоха 5/60 [Тренировка]:   0%|                                                                                …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 5: Train Loss=3.9939, Train Lev=8.9206, Val Loss=3.9989, Val Lev=8.8780
  Примеры декодирования (Предсказание | Реалность):
    '' | 'ФААР834ОМП'
    '' | 'Т0С ЖЩ0О БМЫ'
    '' | 'ЬЛННЖЗУЯН3ЭХ7'
    '' | 'АИИ9Ъ9ОЭЯЕ'
    '' | '#6ЧФ8ЮО'
    '' | 'ЫЭ# НЬЦЦ'
    '' | '8ЖЭК ЛТЕ'
    '' | '5О4ГЪЦ'
    '' | 'ДФЯЯХЭФ9'
    '' | 'ЧШ9А 8П'
  Val Lev не улучшился (8.8780 vs best 8.8780). Без улучшений: 4/15
--- Эпоха 6/60 ---

Эпоха 6/60 [Тренировка]:   0%|                                                                                …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 6: Train Loss=3.9904, Train Lev=8.9112, Val Loss=3.9948, Val Lev=8.8037
  Примеры декодирования (Предсказание | Реалность):
    'Щ' | 'ФААР834ОМП'
    'Щ' | 'Т0С ЖЩ0О БМЫ'
    'Ъ' | 'ЬЛННЖЗУЯН3ЭХ7'
    '' | 'АИИ9Ъ9ОЭЯЕ'
    '' | '#6ЧФ8ЮО'
    '' | 'ЫЭ# НЬЦЦ'
    '' | '8ЖЭК ЛТЕ'
    '' | '5О4ГЪЦ'
    '' | 'ДФЯЯХЭФ9'
    '' | 'ЧШ9А 8П'
  ✨ Val Lev улучшился: 8.8780 -> 8.8037. Сохранение модели...
    Модель сохранена: model_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.pth
--- Эпоха 7/60 ---

Эпоха 7/60 [Тренировка]:   0%|                                                                                …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 7: Train Loss=3.9868, Train Lev=8.8874, Val Loss=3.9905, Val Lev=8.8540
  Примеры декодирования (Предсказание | Реалность):
    'Г' | 'ФААР834ОМП'
    'Г' | 'Т0С ЖЩ0О БМЫ'
    'Г' | 'ЬЛННЖЗУЯН3ЭХ7'
    '' | 'АИИ9Ъ9ОЭЯЕ'
    '' | '#6ЧФ8ЮО'
    '' | 'ЫЭ# НЬЦЦ'
    '' | '8ЖЭК ЛТЕ'
    '' | '5О4ГЪЦ'
    '' | 'ДФЯЯХЭФ9'
    '' | 'ЧШ9А 8П'
  Val Lev не улучшился (8.8540 vs best 8.8037). Без улучшений: 1/15
--- Эпоха 8/60 ---

Эпоха 8/60 [Тренировка]:   0%|                                                                                …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 8: Train Loss=3.9813, Train Lev=8.8436, Val Loss=3.9902, Val Lev=8.8467
  Примеры декодирования (Предсказание | Реалность):
    '' | 'ФААР834ОМП'
    'О' | 'Т0С ЖЩ0О БМЫ'
    'О' | 'ЬЛННЖЗУЯН3ЭХ7'
    '' | 'АИИ9Ъ9ОЭЯЕ'
    '' | '#6ЧФ8ЮО'
    '' | 'ЫЭ# НЬЦЦ'
    '' | '8ЖЭК ЛТЕ'
    '' | '5О4ГЪЦ'
    '' | 'ДФЯЯХЭФ9'
    '' | 'ЧШ9А 8П'
  Val Lev не улучшился (8.8467 vs best 8.8037). Без улучшений: 2/15
--- Эпоха 9/60 ---

Эпоха 9/60 [Тренировка]:   0%|                                                                                …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 9: Train Loss=3.9607, Train Lev=8.7811, Val Loss=3.9496, Val Lev=8.6950
  Примеры декодирования (Предсказание | Реалность):
    'Ы' | 'ФААР834ОМП'
    'Ы' | 'Т0С ЖЩ0О БМЫ'
    'О5' | 'ЬЛННЖЗУЯН3ЭХ7'
    '35' | 'АИИ9Ъ9ОЭЯЕ'
    'О' | '#6ЧФ8ЮО'
    'О' | 'ЫЭ# НЬЦЦ'
    'О' | '8ЖЭК ЛТЕ'
    '' | '5О4ГЪЦ'
    'О' | 'ДФЯЯХЭФ9'
    'О' | 'ЧШ9А 8П'
  ✨ Val Lev улучшился: 8.8037 -> 8.6950. Сохранение модели...
    Модель сохранена: model_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.pth
--- Эпоха 10/60 ---

Эпоха 10/60 [Тренировка]:   0%|                                                                               …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 10: Train Loss=3.3099, Train Lev=7.7676, Val Loss=1.6151, Val Lev=3.2697
  Примеры декодирования (Предсказание | Реалность):
    'ЗААА83ЮШМЪ' | 'ФААР834ОМП'
    'МС  4#0Г6МЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯНЭХЛ' | 'ЬЛННЖЗУЯН3ЭХ7'
    'ЯИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    'Щ6ЧФ8ЮШ' | '#6ЧФ8ЮО'
    'ЫЭ# ЬЦЦ' | 'ЫЭ# НЬЦЦ'
    'Щ4ЭКЛТ' | '8ЖЭК ЛТЕ'
    'СО4ГЪЦ' | '5О4ГЪЦ'
    'ЯЯЯ5Р9' | 'ДФЯЯХЭФ9'
    '9Ш9АЪ' | 'ЧШ9А 8П'
  ✨ Val Lev улучшился: 8.6950 -> 3.2697. Сохранение модели...
    Модель сохранена: model_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.pth
--- Эпоха 11/60 ---

Эпоха 11/60 [Тренировка]:   0%|                                                                               …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 11: Train Loss=1.0038, Train Lev=1.9215, Val Loss=0.7005, Val Lev=1.4083
  Примеры декодирования (Предсказание | Реалность):
    'РААР83Ж#МЪ' | 'ФААР834ОМП'
    'МС ЖЩ0З БМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХЛ' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#6ЧФ8ЮО' | '#6ЧФ8ЮО'
    'ЫЭ# НЬЦЦ' | 'ЫЭ# НЬЦЦ'
    '8ЖЭК ЛТЕ' | '8ЖЭК ЛТЕ'
    'СО4ГЪЦ' | '5О4ГЪЦ'
    'РЯЯЖЛФ9' | 'ДФЯЯХЭФ9'
    'ЧШ9А 8П' | 'ЧШ9А 8П'
  ✨ Val Lev улучшился: 3.2697 -> 1.4083. Сохранение модели...
    Модель сохранена: model_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.pth
--- Эпоха 12/60 ---

Эпоха 12/60 [Тренировка]:   0%|                                                                               …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 12: Train Loss=0.6280, Train Lev=1.3180, Val Loss=0.5669, Val Lev=1.1827
  Примеры декодирования (Предсказание | Реалность):
    'РААР833ЩМП' | 'ФААР834ОМП'
    'МС ЖЩ0Г БМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХЛ' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#6ЧФ8ЮО' | '#6ЧФ8ЮО'
    'ЫЭ# НЬЦЦ' | 'ЫЭ# НЬЦЦ'
    '8ЖЭК ЛТЕ' | '8ЖЭК ЛТЕ'
    'СО4ГЪЦ' | '5О4ГЪЦ'
    'РЯЯЖЛФ9' | 'ДФЯЯХЭФ9'
    'ЧШ9А 8П' | 'ЧШ9А 8П'
  ✨ Val Lev улучшился: 1.4083 -> 1.1827. Сохранение модели...
    Модель сохранена: model_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.pth
--- Эпоха 13/60 ---

Эпоха 13/60 [Тренировка]:   0%|                                                                               …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 13: Train Loss=0.5357, Train Lev=1.1794, Val Loss=0.4808, Val Lev=1.0540
  Примеры декодирования (Предсказание | Реалность):
    'ГААР83Ю#МП' | 'ФААР834ОМП'
    '0ОС ЖЩ0З БМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХЛ' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#6ЧФ8ЮО' | '#6ЧФ8ЮО'
    'ЫЭ# НЬЦЦ' | 'ЫЭ# НЬЦЦ'
    '8ЖЭК ЛТЕ' | '8ЖЭК ЛТЕ'
    '5О4ГЪЦ' | '5О4ГЪЦ'
    'ФЯЯЖЛФ9' | 'ДФЯЯХЭФ9'
    'ЧШ9А 8П' | 'ЧШ9А 8П'
  ✨ Val Lev улучшился: 1.1827 -> 1.0540. Сохранение модели...
    Модель сохранена: model_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.pth
--- Эпоха 14/60 ---

Эпоха 14/60 [Тренировка]:   0%|                                                                               …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 14: Train Loss=0.4744, Train Lev=1.0659, Val Loss=0.4264, Val Lev=1.0023
  Примеры декодирования (Предсказание | Реалность):
    'ФААР83Ю#МП' | 'ФААР834ОМП'
    'ТОС ЖЩ0З БМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХ7' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#6ЧФ8ЮО' | '#6ЧФ8ЮО'
    'ЫЭ# НЬЦЦ' | 'ЫЭ# НЬЦЦ'
    '8ЖЭК ЛТЕ' | '8ЖЭК ЛТЕ'
    '5О4ГЪЦ' | '5О4ГЪЦ'
    'ЯЯЖЛФ9' | 'ДФЯЯХЭФ9'
    'ЧШ9А 8П' | 'ЧШ9А 8П'
  ✨ Val Lev улучшился: 1.0540 -> 1.0023. Сохранение модели...
    Модель сохранена: model_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.pth
--- Эпоха 15/60 ---

Эпоха 15/60 [Тренировка]:   0%|                                                                               …

   [Валидация]:   0%|                                                                                         …

  Итоги Эпохи 15: Train Loss=0.4394, Train Lev=1.0042, Val Loss=0.4126, Val Lev=0.9487
  Примеры декодирования (Предсказание | Реалность):
    'ФААР83ЮОМЪ' | 'ФААР834ОМП'
    'ТОС ЖЩ0ЗБМЫ' | 'Т0С ЖЩ0О БМЫ'
    'ЬЛННЖЗУЯН3ЭХ7' | 'ЬЛННЖЗУЯН3ЭХ7'
    'АИИ9Ъ9ОЭЯЕ' | 'АИИ9Ъ9ОЭЯЕ'
    '#6ЧФ8ЮО' | '#6ЧФ8ЮО'
    'ЫЭ# НЬЦЦ' | 'ЫЭ# НЬЦЦ'
    '8ЖЭК ЛТЕ' | '8ЖЭК ЛТЕ'
    '5О4ГЪЦ' | '5О4ГЪЦ'
    'ФЯЯЖФ9' | 'ДФЯЯХЭФ9'
    'ЧШ9А 8П' | 'ЧШ9А 8П'
  ✨ Val Lev улучшился: 1.0023 -> 0.9487. Сохранение модели...
    Модель сохранена: model_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.pth
--- Эпоха 16/60 ---

Эпоха 16/60 [Тренировка]:   0%|                                                                               …

!!! Обучение прервано пользователем !!!
==================== Завершение Raw Audio: RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1 ====================

--- Успешное завершение run_training_pipeline_raw для 'RawAudio_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1' ---

--- Обучение Raw Audio (RawAudio_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1) завершено за 4.79 часов ---

--- Итоги Запуска Raw Audio (RawAudio_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1) ---

Сводная таблица результатов:

                                         config_name  best_val_lev  best_epoch       status  train_time_min  infer_time_sec  final_train_loss  final_val_loss error mlflow_run_id                                         model_path
0  RawAudio_RawAudio_SR8k_InConv64k257s16_CNN3x12...        0.9487          15  interrupted          0.0000          0.0000            0.4394          0.4126  None          None  C:\Users\vasja\OneDrive\Рабочий стол\Morse_dev...

--- Результат Обучения Raw Audio ---
  Конфигурация: RawAudio_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1
  Best Val Levenshtein: 0.9487 (Эпоха 15)
  Статус: interrupted
  Модель: C:\Users\vasja\OneDrive\Рабочий стол\Morse_dev\MorseAudioDecoder\output_v13_raw_audio\model_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.pth
  Параметры: C:\Users\vasja\OneDrive\Рабочий стол\Morse_dev\MorseAudioDecoder\output_v13_raw_audio\params_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.json
  Submission: C:\Users\vasja\OneDrive\Рабочий стол\Morse_dev\MorseAudioDecoder\output_v13_raw_audio\submission_greedy_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1.csv
  MLflow Run ID: None

Полные результаты Raw Audio сохранены в CSV: C:\Users\vasja\OneDrive\Рабочий стол\Morse_dev\MorseAudioDecoder\output_v13_raw_audio\raw_audio_run_results_RawAudio_RawAudio_SR8k_InConv64k257s16_CNN3x128_RNN2x256_BiGRU_GELU_LR1e-04_WD1e-04_OptimAdamW_Sched1Cycle_Run1_20250413_1607.csv

--- Ячейка 13 (v13.0 - Исправлено): Завершена ---
--------------------------------------------------